/**:
  ros__parameters:
    links_map:
      base: base_link
      left_front:
        - fl_abad_link
        - fl_upper_leg_link
        - fl_lower_leg_link
        - fl_foot_link

      right_front:
        - fr_abad_link
        - fr_upper_leg_linnk
        - fr_lower_leg_link
        - fr_foot_link

      left_hind:
        - hl_abad_link
        - hl_upper_leg_linnk
        - hl_lower_leg_link
        - hl_foot_link

      right_hind:
        - hr_abad_link
        - hr_upper_leg_link
        - hr_lower_leg_link
        - hr_foot_link