controller_joint_names: ['', 'fl_abad_joint', 'fl_hip_joint', 'fl_knee_joint', 'fr_abad_joint', 'fr_hip_joint', 'fr_knee_joint', 'hr_abad_joint', 'hr_hip_joint', 'hr_knee_joint', 'hl_abad_joint', 'hl_hip_joint', 'hl_knee_joint', ]
