"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - fl_abad_joint
          - fl_hip_joint
          - fl_knee_joint
          - fr_abad_joint
          - fr_hip_joint
          - fr_knee_joint
          - hl_abad_joint
          - hl_hip_joint
          - hl_knee_joint
          - hr_abad_joint
          - hr_hip_joint
          - hr_knee_joint

      gains:
        fl_abad_joint : {p: 180, d: 0.9, i: 20}
        fl_hip_joint : {p: 180, d: 0.9, i: 20}
        fl_knee_joint : {p: 180, d: 0.9, i: 20}
        fr_abad_joint : {p: 180, d: 0.9, i: 20}
        fr_hip_joint : {p: 180, d: 0.9, i: 20}
        fr_knee_joint : {p: 180, d: 0.9, i: 20}
        hl_abad_joint : {p: 180, d: 0.9, i: 20}
        hl_hip_joint : {p: 180, d: 0.9, i: 20}
        hl_knee_joint : {p: 180, d: 0.9, i: 20}
        hr_abad_joint : {p: 180, d: 0.9, i: 20}
        hr_hip_joint : {p: 180, d: 0.9, i: 20}
        hr_knee_joint : {p: 180, d: 0.9, i: 20}
